In [4]:
import numpy as np

In [5]:
x=np.array([10,20,30])          #creating numpy array 

In [6]:
x

array([10, 20, 30])

In [7]:
type(x)

numpy.ndarray

In [8]:
a =np.array([[10,20,30],[40,50,60]])

In [9]:
a

array([[10, 20, 30],
       [40, 50, 60]])

In [10]:
#difrence between numpy array and list
#list-slow works
#numpy array-fast works


In [11]:
%timeit [i*i for i in range(1000)]

155 µs ± 13.5 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [12]:
arr1=np.arange(1000)

In [13]:
%timeit arr1*4


4.69 µs ± 519 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [14]:
a=np.array([1,2,3,4,5])


In [15]:
a

array([1, 2, 3, 4, 5])

In [16]:
list1=np.array([10,20,30,40])
list1

array([10, 20, 30, 40])

In [17]:


type(list1)

numpy.ndarray

In [18]:



array1=np.array(list1)

In [19]:
array1

array([10, 20, 30, 40])

In [20]:
type(array1)

numpy.ndarray

In [21]:
#check dimension of an array
array1.ndim

1

In [22]:
#print the shape of an array in the form-r,c
array1.shape

(4,)

In [23]:
array2=np.array([[10,20,30,40],[50,60,70,80]])

In [24]:
array2

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [25]:



type(array2)

numpy.ndarray

In [26]:

array2.ndim

2

In [27]:

array2.shape   # no. of elements in each dimension
                 # no. of rows and columns

(2, 4)

In [28]:
array2.size     #gives the count of total number of element in an array

8

<h1>DATA TYPE</h1>

In [29]:
a=np.array(['1','2','3'],dtype=int)


In [30]:
a

array([1, 2, 3])

In [31]:
b=np.array(['1','2','3'],dtype=float)

In [32]:
b

array([1., 2., 3.])

In [33]:
c=np.array([23,54,77],dtype=str)

In [34]:
c

array(['23', '54', '77'], dtype='<U2')

In [35]:
a1=np.array([[1,2,3],[4,5],'anish',1000],dtype=object)

In [36]:
a1

array([list([1, 2, 3]), list([4, 5]), 'anish', 1000], dtype=object)

In [37]:
a1.ndim

1

In [38]:
a1.shape

(4,)

In [39]:
a1.size

4

In [40]:
#arange array---->


In [41]:
## np.array([[1,2,3,4,5], [6,7,8,9,10],......., [46,47,48,49,50]])
array3=np.arange(50)

In [42]:
array3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [43]:
array3.shape

(50,)

In [44]:
array3.size

50

In [45]:
array3=np.arange(50).reshape(10,5)

In [46]:
array3

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [47]:
a2=np.array([1.9,2.0,3.6],dtype=int)

In [48]:
a2

array([1, 2, 3])

In [49]:
a=np.array([2,3,'anish'],dtype='object')

In [50]:
a

array([2, 3, 'anish'], dtype=object)

<h1>Element-Wise arithmatic opration </h1>

In [51]:
a=[1,2,3,4,5]

In [52]:
array4=np.array(a)


In [53]:
array4**2

array([ 1,  4,  9, 16, 25])

In [54]:
array4+10

array([11, 12, 13, 14, 15])

In [55]:
array4/4

array([0.25, 0.5 , 0.75, 1.  , 1.25])

<h1>Indexing</h1>

In [56]:
a=np.array([24,34,56,88,78,30,46,23,44])

In [57]:
a


array([24, 34, 56, 88, 78, 30, 46, 23, 44])

In [58]:
a[0]

24

In [59]:
a[5]

30

In [60]:
a[-5]

78

In [61]:
b = a.reshape(3,3)

In [62]:
b

array([[24, 34, 56],
       [88, 78, 30],
       [46, 23, 44]])

In [63]:
b[0]

array([24, 34, 56])

In [64]:
b[0][0]

24

In [65]:
b[-1]

array([46, 23, 44])

In [66]:
b[-1][-1]

44

In [67]:
#providing list of indexing
b[[0,2]]

array([[24, 34, 56],
       [46, 23, 44]])

<h1>SLICING</h1>

In [68]:
a

array([24, 34, 56, 88, 78, 30, 46, 23, 44])

In [69]:
a[:]

array([24, 34, 56, 88, 78, 30, 46, 23, 44])

In [70]:
a[:-2]

array([24, 34, 56, 88, 78, 30, 46])

In [71]:
b

array([[24, 34, 56],
       [88, 78, 30],
       [46, 23, 44]])

In [72]:
b[:]

array([[24, 34, 56],
       [88, 78, 30],
       [46, 23, 44]])

In [73]:
b[:-2]

array([[24, 34, 56]])

In [74]:
#Filter element between rows and columns
#array[rows column]
b[:,:]

array([[24, 34, 56],
       [88, 78, 30],
       [46, 23, 44]])

In [75]:
b[1:,1:]

array([[78, 30],
       [23, 44]])

In [76]:
b[-1:,-1:]

array([[44]])

In [77]:
b[0:2,2:]

array([[56],
       [30]])

<h1>Masking</h1>

In [78]:
array4=np.arange(1,21).reshape(4,5)

In [79]:
array4

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [80]:
#Filter evens
array4[array4%2==0]


array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [81]:
#Filter odds
array4[array4%2==1]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [82]:
array4

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [83]:
array4[array4>=15]

array([15, 16, 17, 18, 19, 20])

In [84]:
age=np.arange(12,52).reshape(10,4)

In [85]:
age

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39],
       [40, 41, 42, 43],
       [44, 45, 46, 47],
       [48, 49, 50, 51]])

In [86]:
#To check eligibilty for vote
age[age>=18]

array([18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51])

In [87]:
age[age>30]


array([31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
       48, 49, 50, 51])

In [88]:
age[-1]

array([48, 49, 50, 51])

In [89]:
age[+2]

array([20, 21, 22, 23])

In [90]:
age[-1][age[-1]<50]

array([48, 49])

In [91]:
age[-1][0][age[-1][0]==48]
age[-1][0][age[-1][0]!=48]

array([], dtype=int32)

In [92]:
#Reshape
a1= np.arange(32)

In [93]:
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [94]:
a1.shape

(32,)

In [95]:
a2=a1.reshape(1,-1)

In [96]:
a2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31]])

In [97]:
a2.shape

(1, 32)

In [98]:
a2.reshape(4,-1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

<h1>Aggregate function</h1>
max, min, sum, mean, std etc........

In [99]:
a=np.arange(10).reshape(2,-1)

In [100]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [101]:
#Find the all element of sum
a.sum()

45

In [102]:
#Smallest element of array
a.min()

0

In [103]:
#Greatest element of array
a.max()

9

In [104]:
#Calculate the average of all nos.
a.mean()

4.5

In [105]:
#Calculate the standard of all deviation
a.std()


2.8722813232690143

In [106]:
np.sum(a)

45

In [107]:
np.max(a)

9

In [108]:
np.min(a)

0

In [109]:
np.mean(a)

4.5

In [110]:
np.std(a)

2.8722813232690143

<h1>np.where - used to return the indices of all non-zero element</h1>

In [111]:
arr=np.array([1,0,9,-3,5,6,0,0,3,-4,0,4,8,7])

In [112]:
np.where(arr)

(array([ 0,  2,  3,  4,  5,  8,  9, 11, 12, 13], dtype=int64),)

In [113]:
#it can also be used to return the elements based on a specific condition
arr

array([ 1,  0,  9, -3,  5,  6,  0,  0,  3, -4,  0,  4,  8,  7])

In [114]:
np.where(arr<0, '-ve','+ve')

array(['+ve', '+ve', '+ve', '-ve', '+ve', '+ve', '+ve', '+ve', '+ve',
       '-ve', '+ve', '+ve', '+ve', '+ve'], dtype='<U3')

<h2>np.any-return true if any one element inside an array meets the desired condition</h2>

In [115]:
np.any(arr>10)

False

In [116]:
np.any(arr%2==0)

True

In [117]:
np.any(arr<0)

True

<h2>np.all-return true if all the element inside an array meets the desired condtion</h2>

In [118]:
np .all(arr<10)

True

In [119]:
np.all(arr%2==0)


False

In [120]:
np.all(arr<0)


False

In [121]:
np.all(arr<5)

False

<h2>np.sort()-used to sort an array</h2>

In [122]:
a=np.array([4, 7, 0, 3, 8, 2, 9, 1, 6, 5])

In [123]:
a

array([4, 7, 0, 3, 8, 2, 9, 1, 6, 5])

In [124]:
np.sort(a)  #it does not make a permanent change

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [125]:
a

array([4, 7, 0, 3, 8, 2, 9, 1, 6, 5])

In [126]:
# this will make a permanent change like lists in python
a.sort()

In [127]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

<h2>Argsort(), Argmax(), Argmin()</h2>

In [128]:
a=np.array([4, 7, 0, 3, 8, 2, 9, 1, 6, 5])

In [129]:
a

array([4, 7, 0, 3, 8, 2, 9, 1, 6, 5])

In [130]:
np.argsort(a)

array([2, 7, 5, 3, 0, 9, 8, 1, 4, 6], dtype=int64)

In [131]:
a.argsort()

array([2, 7, 5, 3, 0, 9, 8, 1, 4, 6], dtype=int64)

In [132]:
# sort a 2D array
array2=np.array([[1,2,3],[2,0,2]])

In [133]:
array2

array([[1, 2, 3],
       [2, 0, 2]])

In [134]:
np.sort(array2)  #2D array sorts each row by default

array([[1, 2, 3],
       [0, 2, 2]])

In [135]:
array2

array([[1, 2, 3],
       [2, 0, 2]])

In [136]:
#sort a 2D array column wise
np.sort(array2,axis=0)


array([[1, 0, 2],
       [2, 2, 3]])

In [137]:
# in numpy
# axis = 0 means columns
# axis = 1 means rows

# in pandas
# axis = 1 columns
# axis = 0 rows



In [138]:
# argmax() - returns the index of maximum element
np.argmax(a)

6

In [139]:
a.argmax()

6

In [140]:
# argmin() - returns the index of manimum element
np.argmin(a)


2

In [141]:
a.argmin()

2

<h2>Matrix Multiplication</h2>

In [142]:
a=np.array([[34,45,22],[67,99,90]])

In [143]:
a

array([[34, 45, 22],
       [67, 99, 90]])

In [144]:
b=np.array([[1,2,3],[4,5,6],[23,34,22]])


In [145]:
b

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [23, 34, 22]])

In [146]:
a.shape, b.shape

((2, 3), (3, 3))

In [147]:
np.matmul(a,b)


array([[ 720, 1041,  856],
       [2533, 3689, 2775]])

In [148]:
np.dot(a,b)

array([[ 720, 1041,  856],
       [2533, 3689, 2775]])

In [149]:
a.dot(b)

array([[ 720, 1041,  856],
       [2533, 3689, 2775]])

<h1>Vectorize</h1>

In [150]:
arr=np.array([23,22,34,45,556])
arr

array([ 23,  22,  34,  45, 556])

In [151]:
def myfunc(a):
    if a%2==0:
        return 'even'
        
    else:
        return 'odd'

In [153]:
Even_odd=np.vectorize(myfunc)

In [156]:
Even_odd(arr)

array(['odd', 'even', 'even', 'odd', 'even'], dtype='<U4')

In [158]:
from math import *
power=np.vectorize(pow)

In [159]:
power(arr,2)

array([   529.,    484.,   1156.,   2025., 309136.])

In [160]:
power(arr,29)

array([3.09105864e+39, 8.51643319e+38, 2.58754907e+44, 8.77329837e+47,
       4.04733317e+79])

<h2>Tile function-repeat multiple row and column</h2>
np.tile(no. of times row need to repeat and no. of times column need to repeat)

In [174]:
arr = np.arange(10,40,10)

In [175]:
np.tile(arr,(4,1))

array([[10, 20, 30],
       [10, 20, 30],
       [10, 20, 30],
       [10, 20, 30]])

In [176]:
np.tile(arr,(5,3))

array([[10, 20, 30, 10, 20, 30, 10, 20, 30],
       [10, 20, 30, 10, 20, 30, 10, 20, 30],
       [10, 20, 30, 10, 20, 30, 10, 20, 30],
       [10, 20, 30, 10, 20, 30, 10, 20, 30],
       [10, 20, 30, 10, 20, 30, 10, 20, 30]])

<h1> Broadcasting</h1>

In [191]:
a=np.arange(1,13).reshape(-1,3)

In [192]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [193]:
b=np.array((5,2,3))

In [194]:
b

array([5, 2, 3])

In [196]:
a+b     #Here b array is broadcasting automatically

array([[ 6,  4,  6],
       [ 9,  7,  9],
       [12, 10, 12],
       [15, 13, 15]])

In [ ]:
# np.tile() function do broadcasting as it repeats rows or columns many times

<h1>Splitting</h1>

In [204]:
a=np.arange(9)


In [205]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [206]:
a.size

9

In [210]:
np.split(a,3) #np.split(a,3)    #this will raise an error

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [211]:
# for splitting an array into unequal parts use list of index

In [212]:
b=np.arange(14)


In [213]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [216]:
x=np.split(b,[3,11])

In [217]:
x

[array([0, 1, 2]),
 array([ 3,  4,  5,  6,  7,  8,  9, 10]),
 array([11, 12, 13])]

In [218]:
y=np.split(b,[2,3,4,5,11,14])

In [220]:
y           # 14th index is not present so it will return an empty array

[array([0, 1]),
 array([2]),
 array([3]),
 array([4]),
 array([ 5,  6,  7,  8,  9, 10]),
 array([11, 12, 13]),
 array([], dtype=int32)]

<h1>Horizontal split</h1>

In [224]:
x=np.arange(16).reshape(4,4)

In [225]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [229]:
np.hsplit(x,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [231]:
np.hsplit(x,[2,3,6]) #index wise splitting

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]]),
 array([], shape=(4, 0), dtype=int32)]

<h1>Vartical split</h1>

In [236]:
np.vsplit(x,4)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [237]:
np.vsplit(x,[2,3,6])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]]),
 array([], shape=(0, 4), dtype=int32)]